name: java_codes_test_workflow
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name : Get_code
        uses: actions/checkout@v3
      - name : Set_up_JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: compile_java_code
        run: javac Main.java
      - name: run_java_code
        run:  java Main
