name: Connectivity Check via Nettools
on:
 workflow_dispatch:
   inputs:
     environment:
      description: Choose Environment
      type: choice
      options:
       - dev
       - load
       - prod
      required: true
     endpoint:
      description: Choose endpoint
      type: choice
      options:
       - ping
       - socket
       - traceroute
       - dns
       - curl
       - ciphertest
       - certest
      required: true
     host:
      description: Enter host
      type: string
      required: true
     port:
      description: Enter port (required for socket,ciphertest,certest)
      type: string
      required: false
     
